---
- name: Install commonly used python packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-neutronclient

- name: Install commonly used python3 packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3-neutronclient
  when: releasever > 15
