---
- name: Install tools for packagers
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - graphviz
    - copr-cli
    - mock
    - rpm-build
    - rpmdevtools
    - flatpack
    - gdb
    - pkgdiff
    - fedora-review
    - scl-utils-build
    - fedora-repos-rawhide
    - module-build-service
    - pyp2rpm
    - origin-clients
    - modtools
    - atomic-reactor
    - krb5-devel
    - python-novaclient

- name: Enable repositories for SCLo variant of centpkg
  shell: |
    dnf -y copr enable hhorak/centpkg-sclo

- name: Install tools for packagers
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - centos-packager

