---
- name: Install tools for packagers
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - graphviz
    - copr-cli
    - mock
    - rpm-build
    - rpmdevtools
    - gdb
    - pkgdiff
    - scl-utils-build
    - pyp2rpm
    - krb5-devel
  tags:
    - packager

- name: Install tools for packagers (Fedora only)
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - flatpack
    - fedora-repos-rawhide
    - module-build-service
    - modtools
    - fedora-review
  tags:
    - packager
  when:
    - distro == 'fedora'

- name: Enable repositories for SCLo variant of centpkg
  shell: |
    dnf -y copr enable hhorak/centpkg-sclo
  tags:
    - packager
  when:
    - distro == 'fedora'

- name: Enable copr with centpkg-sclo
  get_url:
    url: http://copr.fedorainfracloud.org/coprs/hhorak/centpkg-sclo/repo/epel-{{ releasever }}/hhorak-centpkg-sclo-epel-{{ releasever }}.repo
    dest: /etc/yum.repos.d/hhorak-centpkg-sclo-epel-{{ releasever }}.repo
  tags:
    - packager
  when:
    - distro == 'centos'

- name: Install tools for packagers
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - centos-packager
  tags:
    - packager

