---
- name: Install basic tools
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - vim-enhanced
    - git
    - wget
    - rsync
    - perl
    - perl-Git
    - jpackage-utils
    - java
    - ca-certificates
    - ntp
    - "@Development Tools"

- name: Install basic apps
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - gimp
    - inkscape
    - '@LibreOffice'

- name: Run the basic services
  service:
    state: started
    name: "{{ item }}"
    enabled: yes
  with_items:
    - ntpd

- name: Install basic usage
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - gitk
    - terminator
    - hwdata
    - tuned
    - lm_sensors
    - p7zip
    - sqlite
    - jq
    - yum-utils
    - yamllint

- name: Install commonly used python packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-devel
    - python-future
    - python-bugzilla-cli
    - python-bugzilla
    - python-requests-kerberos
    - python-unicodecsv
    - python3
    - python3-click
    - python3-devel
    - python3-flask
    - python3-future
    - python3-bugzilla
    - python3-GitPython
    - python3-requests-kerberos
    - python3-unicodecsv
    - python3-neutronclient
    - python2-neutronclient

- name: install the rpmfusion repo packages
  yum: name={{ item }}
       state=present
  with_items:
    - http://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ releasever }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ releasever }}.noarch.rpm

- name: install packages from rpmfusion
  yum: name={{ item }}
       state=present
  with_items:
    - vlc
