---
- name: Set the hostname
  action: shell hostname {{ ansible_hostname }}

- name: set timezone to Europe/Prague
  timezone:
    name: Europe/Prague

- name: Install some extra basic tools
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
  when: releasever > 10
